Tests
vmwhoami/react-calculator pull request #7
Opened 2021-02-22 21:29 UTC by vmwhoami

Setup the tests for my project.
Added unit tests for your calculate.js file.
Elements are displayed at:
Home page
Calculator page
Quote page by using jest snapshots.

Sorry about the last pull request I was in a hurry and didn't bother to check the branch

2021-02-22 22:31 UTC, krys2fa requested changes
## Nicely done @vmwhoami  👏 
You wrote tests covering both components and logic. 💪 

### Status: Changes Required ♻️ 
Check the comments below for the requested changes.

Please request another review after implementing the changes.

Happy Coding 🖥️  😃 

###### You can contact me on slack (Chris Amanor) for any clarification.

2021-02-22 22:31 UTC, krys2fa commented on src/__test__/calculate.test.js
> +});
- [ ] [REQUIRED] Even though the tests here are different, the test descriptions are the same. Please correct this.

2021-02-22 22:31 UTC, krys2fa commented on src/__test__/calculate.test.js
> +
- [ ] [REQUIRED] Even though the tests here are different, the test descriptions are the same. Please correct this.

2021-02-22 22:31 UTC, krys2fa commented on src/logic/calculate.js
> +  // convToString(total, next, operation)
- [ ] [REQUIRED]  It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2021-02-23 07:14 UTC, mikenath223 approved these changes
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

2021-02-23 08:11 UTC, merged